language: java

jdk: openjdk8

env:
   global:
      - ACTIVE_PROFILES="-Pjacoco" ADDITIONAL_MAVEN_ARGS="coveralls:report sonar:sonar"

addons:
   sonarcloud:
      organization: "cosimogiani-github"

install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
    - mvn -f museum-project/pom.xml $ACTIVE_PROFILES clean verify $ADDITIONAL_MAVEN_ARGS