language: java

jdk: openjdk8

addons:
   sonarcloud:
      organization: "cosimogiani-github"

install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
    - mvn -f museum-project/pom.xml -Pjacoco clean verify coveralls:report sonar:sonar